version: '3'

services:
  app:
    build: ./
    container_name: fastapi-sqlite1
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    restart: always
    volumes:
      - sqlite-data:/data
    ports:
      - "8000:8000"
  app2:
    image: fastapi-sqlite-app
    container_name: fastapi-sqlite2
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    restart: always
    volumes:
      - sqlite-data:/data
    ports:
      - "8001:8000"

volumes:
  sqlite-data:
